# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/core/protos/vision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/core/protos/vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pp/core/protos/vision.proto\x12\x06vision\"4\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x95\x01\n\x15\x45xtractedTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12=\n\x08metadata\x18\x02 \x03(\x0b\x32+.vision.ExtractedTextResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32U\n\x0fVisionProcessor\x12\x42\n\x0b\x45xtractText\x12\x14.vision.ImageRequest\x1a\x1d.vision.ExtractedTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.core.protos.vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTEDTEXTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_EXTRACTEDTEXTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_IMAGEREQUEST']._serialized_start=40
  _globals['_IMAGEREQUEST']._serialized_end=92
  _globals['_EXTRACTEDTEXTRESPONSE']._serialized_start=95
  _globals['_EXTRACTEDTEXTRESPONSE']._serialized_end=244
  _globals['_EXTRACTEDTEXTRESPONSE_METADATAENTRY']._serialized_start=197
  _globals['_EXTRACTEDTEXTRESPONSE_METADATAENTRY']._serialized_end=244
  _globals['_VISIONPROCESSOR']._serialized_start=246
  _globals['_VISIONPROCESSOR']._serialized_end=331
# @@protoc_insertion_point(module_scope)
